on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    name: Run Haxe DevEnv.hxml (checks null-safety)
    steps:
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: latest

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install & Check Haxe
        run: haxe -version

      - name: Test Dev. Environment
        run: haxe DevEnv.hxml
