on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  haxe_4:
    runs-on: ubuntu-latest
    name: Run Haxe (4.3.7) test/Test.hxml (on js, cpp, and hl)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/run_test
        with:
          haxe-version: 4.3.7

  haxe_latest:
    runs-on: ubuntu-latest
    name: Run Haxe (latest) test/Test.hxml (on js, cpp, and hl)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/run_test
        with:
          haxe-version: latest
